### ISSUE TITLE
Fix AppVeyor CI script to scan for files and fail build on syntax error

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337-strategies#1]
File to fix: `appveyor.yml`

There are two goals:
- For each `.mqh` file (including submodules) run the compiler/syntax checker (e.g. using `metaeditor`).
- When compiler fails to compile one of the files, the whole build script should fail. You can use `forfiles` usually returns all the time the successful build.

Current CI test results can be found in [here](https://ci.appveyor.com/project/kenorb/ea31337-strategies/build/1.0.6).

You can test that as part of the PR, or you can also clone the repo, activate CI tests on your fork and test it.

**Comment by kenorb** [comment]
codemill$33

**Comment by ryu0** [comment]
I saw the bounty over at bounysource. Is this still needing to be done?

**Comment by kenorb** [comment]
Yes.

**Comment by ghost** [comment]
I have created a pull request with what seems to be an appropriate fix for this issue. It appears to pass the tests from AppVeyor, though it fails the Travis tests. Does this resolve your issue?

**Comment by kenorb** [comment]
@ryu0 Success scenario also failed as per: https://ci.appveyor.com/project/kenorb/ea31337-strategies/build/1.0.21

Sorry:)

**Comment by kenorb** [comment]
I've created `ci2` branch, uploaded `Test.mq5` file which compiles fine, and modifies your test to point to one file.

See: https://github.com/EA31337/EA31337-strategies/commit/5caccca299c66a34e91bd92292d9bed023450be9

**Comment by ryu0** [comment]
Ok. I'll take a look.

**Comment by kenorb** [comment]
I think the issue is how `metaeditor` is badly designed. Its exit code is basically the number of files being successfully compiled.
So if `metaeditor` compiled one file, it'll return exit code 1, which is the error (which is actually not). I think we just need to ignore the exit code from the `metaeditor`, so it can progress further, so we can test `findstr` logic.

**Comment by ryu0** [comment]
I presume so too. I'll see what that requires.

**Comment by kenorb** [comment]
I've fixed it, now it fails on your part.

See: https://ci.appveyor.com/project/kenorb/ea31337-strategies/build/1.0.22

> Result 0 error(s), 0 warning(s)

No compilation errors, but it fails. It should only fail on the compilation warnings or errors.

**Comment by ghost** [comment]
Alright. I'll try something else for that line.

**Comment by kenorb** [comment]
For easier testing, I've created two branches: `ci-fail` and `ci-success`.

Currently `ci-fail` has success on errors as per: https://ci.appveyor.com/project/kenorb/ea31337-strategies/build/1.0.25 (this is incorrect).

And `ci-success` got success on successful compilation as expected: https://ci.appveyor.com/project/kenorb/ea31337-strategies/build/1.0.26 (this is correct).

**Comment by kenorb** [comment]
I think it works now.
- `ci-success`: https://ci.appveyor.com/project/kenorb/ea31337-strategies/build/1.0.28
- `ci-fail`: https://ci.appveyor.com/project/kenorb/ea31337-strategies/build/1.0.29

**Comment by kenorb** [comment]
Fixed by #6.
